### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by taivop** [taivop/eth-nlp-project#56]
Prolly copy stuff from our report

**Comment by AndreiBarsan** [comment]
I also updated your TODO to link to the actual paper in #58. Anything else that needs to be done?

**Comment by taivop** [comment]
Perhaps we could add more under 'Important classes' but it's not a high priority. Otherwise seems OK.

**Comment by AndreiBarsan** [comment]
Yeah, I guess they'll contact us in case they want to run the code but something doesn't work.

**Comment by AndreiBarsan** [comment]
I think the README is OK for now.
